dat<- read.csv('gccres.csv')
attach(data)
attach(dat)
origrate <- origcov/origtslen
newrate <- newcov/newtslen
newrate <- newcoverage/newtslen
boxplot(newrate, origrate)
boxplot(newrate~treatment)
boxplot(newrate*100~treatment)
boxplot(newrate, origrate)
boxplot(newrate/origrate)
boxplot(newrate*100/origrate)
boxplot(newrate*100/origrate, main='newcoragerate/oldcoveragerate')
boxplot(newrate/origrate, main='newcoragerate/oldcoveragerate')
png('newcoverageratio.png')
boxplot(newrate/origrate, main='newcoragerate/oldcoveragerate')
dev.off()
boxplot((newrate-origrate)/origrate, main='newcoragerate/oldcoveragerate')
boxplot((newrate-origrate)/origrate, main='(newcoragerate-origrate)/oldcoveragerate')
png('newcoverageratio2.png')
boxplot((newrate-origrate)/origrate, main='(newcoragerate-origrate)/oldcoveragerate')
dev.off()
boxplot((newrate-origrate)/origrate~treatment, main='(newcoragerate-origrate)/oldcoveragerate')
boxplot((newrate)/origrate~treatment, main='(newcoragerate-origrate)/oldcoveragerate')
boxplot((newrate-origrate)/origrate~treatment, main='(newcoragerate-origrate)/oldcoveragerate')
boxplot(newratee~treatment, main='(newcoragerate-origrate)/oldcoveragerate')
boxplot(newrate~treatment, main='(newcoragerate-origrate)/oldcoveragerate')
boxplot(newratee/origrate~treatment, main='(newcoragerate-origrate)/oldcoveragerate')
boxplot(newratee/origrate~treatment, main='(newcoragerate-origrate)/oldcoveragerate')
boxplot(newrate/origrate~treatment, main='(newcoragerate-origrate)/oldcoveragerate')
boxplot(newrate/origrate~treatment, main='newcoragerate/oldcoveragerate')
boxplot(newrate/origrate~treatment, main='newcoragerate/oldcoveragerate (per treatment)')
png('pertreatmentration')
boxplot(newrate/origrate~treatment, main='newcoragerate/oldcoveragerate (per treatment)')
dev.off()
boxplot((newrate-origrate)/origrate~treatment, main='(newcoragerate-oldcovaragerate)/oldcoveragerate (per treatment)')
png('pertreatmentration2')
boxplot((newrate-origrate)/origrate~treatment, main='(newcoragerate-oldcovaragerate)/oldcoveragerate (per treatment)')
dev.off()
boxplot(newrate/origrate~treatment, main='newcoragerate/oldcoveragerate (per treatment)')
summary
summary()
summary(newrate)
summary(origrate)
